# Problem 1. 
### Write a function that accepts a list of numbers as input and returns a new list with the minimum, maximum, and average of the original list (in that order). Remember to use floating point division to calculate the average. Can you implement this function in a single line?

In [26]:
#define the function
def my_func(a):
    return [min(a), max(a), float(sum(a))/float(len(a))]
list = [1, 2, 3, 12, 15]

In [27]:
#implement on a single line:
new_list = my_func(list)

In [28]:
#display result
new_list

[1, 15, 6.6]

# Problem 2. 
## Python has several methods that seem to change immutable objects. These methods actually work by making copies of objects. We can therefore determine which object types are mutable and which are immutable by using the equal sign and “changing” the objects.

In [51]:
num = 3
new_num = num
new_num= new_num+1
if num == new_num:
    print('numbers are mutable')
else:
    print('numbers are unmutable')
    
string = 'word'
new_string = string
new_string= new_string + 's'
if string == new_string:
    print('strings are mutable')
else:
    print('strings are unmutable')
    
list = [1, 2, 3]
new_list = list
new_list.append(5)
if list == new_list:
    print('lists are mutable')
else:
    print('lists are unmutable')

tuple = (1,2)
new_tuple = tuple
new_tuple = new_tuple + (1,)
if tuple == new_tuple:
    print('tuples are mutable')
else:
    print('tuples are unmutable')
    
dict = {1: 'first', 2: 'second'}
new_dict = dict
new_dict[1] = 'a'
if dict == new_dict:
    print('dicts are mutable')
else:
    print('dicts are unmutable')

numbers are unmutable
strings are unmutable
lists are mutable
tuples are unmutable
dicts are mutable


## Problem 3. 

### Create a module called calculator.py. Write a function that returns the sum of two arguments, a function that returns the product of two arguments, and a function that returns the square root of a single argument. When the file is either run or imported, nothing should be executed. In your main solutions file, import your new calculator module. Using only the functions defined in the module, write a new function that calculates the length of the hypotenuse of a right triangle given the lengths of the other two sides.

In [5]:
#see calc.py (saved in Problem Sets 2 folder)
import calc

def hypot(side1, side2):
    return calc.sqroot(calc.add(calc.prod(side1, side1), calc.prod(side2, side2)))

c= hypot(10, 10)
print('side 3 = ', c)

side 3 =  14.142135623730951


## Problem 1. 
### NumPy’s dot() function performs matrix multiplication. Write a function that defines the following matrices as NumPy arrays.

$$
A = \begin{bmatrix}
    3 & -1 & 4 & \\
    1 & 5 & -9       
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
    2 & 6 & -5 & 3\\
    5 & -8 & 9 & 7\\
    9 & -3 & -2 & -3\\
    \end{bmatrix}
$$

## Return the matrix product AB. 

In [23]:
import numpy as np

def matrix_mult():
    A = np.array([[3, -1, 4], [1, 5, -9]])
    B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
    AB = np.dot(A, B)
    print(AB)

matrix_mult()

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


## Problem 2. 
### Write a function that defines the following matrix as a NumPy array.

$$
A = \begin{bmatrix}
    3 & 1 & 4 \\
    1 & 5 & 9 \\
   -5 & 3 & 1 \\
    \end{bmatrix}
$$


### Return the matrix $-A^3 + 9A^2 - 15A$. 

In [28]:
def my_matrix(a, b, c):
    A = np.array([a, b, c])
    polynomial = -1 * np.dot(A, A, A) + 9 * np.dot(A, A) - 15 * A
    return polynomial
    

In [29]:
my_matrix([3, 1, 4], [1, 5, 9], [-5, 3, 1])

array([[         -27605,         -414634,      1588614741],
       [        3941135,        59673436,   -236730944844],
       [    -6178200150,    -95680965243, 384775326868907]])

## Problem 5. 
### Write a function that defines the following matrices as NumPy arrays.

$$
A = 
\begin{bmatrix}
    0 & 2 & 4 \\ 
    1 & 3 & 5
\end{bmatrix}
$$

$$
B = 
\begin{bmatrix}
3 & 0 & 0\\ 3 & 3 & 0\\ 3 & 3 & 3
\end{bmatrix}
$$


$$
C =
\begin{bmatrix}
    -2 & 0 & 0 \\ 
     0 & -2 & 0 \\ 
     0 & 0 & -2
\end{bmatrix}
$$

### Use NumPy's stacking functions to create and return the block matrix:

$$
\begin{bmatrix}
    0 & A^{T} & I \\
    A & 0 & 0 \\
    B & 0 & C
\end{bmatrix}
$$

### where I is the identity matrix of the appropriate size and each 0 is a matrix of all zeros, also of appropriate sizes. A block matrix of this form is used in the Interior Point method for linear optimization.

In [82]:
def block_array():
    A = np.array([[0, 2, 4], [1, 3, 5]])
    B = np.array([[3, 0, 0], [3, 3, 0], [3, 3, 3]])
    C = np.array([[-2, 0, 0], [0, -2, 0], [0, 0, -2]])
    
    stack1 = np.vstack((np.zeros((3,3)) ,np.vstack((A, B))))
    stack2 = np.vstack((A.T, np.zeros((5,2))))
    stack3 = np.vstack((np.eye(3), np.zeros((2, 3)), C))
    final = np.hstack((stack1, stack2, stack3))
    print(final)
block_array()

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


## Problem 1. 
### Expand the Backpack class to match the following specifications.
1. Modify the constructor so that it accepts a name, a color, and a maximum size (in that order). Make max_size a default argument withdefault value 5. Store each input as an attribute.

2. Modify the put() method to ensure that the backpack does not go over capacity. If the user tries to put in more than max_size items, print “No Room!” and do not add the item to the contents list.

3. Add a new method called dump() that resets the contents of the back- pack to an empty list. This method should not receive any arguments (except self ).

### To ensure that your class works properly, consider writing a test function outside outside of the Backpack class that instantiates and analyzes a Backpack object. Your function may look something like this:

In [130]:
class Backpack(object):
    def __init__(self, name, color, max_size = 5): #max_size set to 5
        self.name = name
        self.contents = []
        self.color = color #adds color
        self.max_size = max_size # adds max size
        
    def put(self, item):
        if len(self.contents) >= self.max_size:
            print('No Room!')
        if len(self.contents) < self.max_size:
            self.contents.append(item)
            
    def take(self, item):
        self.contents.remove(item)
        
    def dump(self):
        self.contents = []
        

### Testing each method in the class

In [132]:
testpack = Backpack("Justin", "Red")
for item in ["pen", "paper", "book", "computer", "eraser", "marker"]:
    testpack.put(item)
print('contents = ', testpack.contents)
#attempting to add 6th items returns the No Room! error. contents of test pack are the first 5 items in the list.

No Room!
contents =  ['pen', 'paper', 'book', 'computer', 'eraser']


In [133]:
testpack.take('paper')
print(testpack.contents)
#paper is removed from testpack

['pen', 'book', 'computer', 'eraser']


In [134]:
testpack.dump()
print(testpack.contents)
#all contents removed

[]
