Numeric types

In [2]:
three = 3 #integer

In [4]:
type(three)

int

In [5]:
three = float(3) #overrides integer type to create a float type
type(three)

float

In [6]:
x=2
y=5
x + y

7

In [7]:
x ** y #x^y

32

In [9]:
drop = False #Boolean, special case (0,1) of int
type(drop)

bool

In [11]:
drop == 0 #False is interchangeable with 0, True is 1

True

In [13]:
x * drop #interaction between x and drop

0

In [14]:
drop2 = bool(0) #overrides automatic integer assignment
type(drop2)

bool

Sequences

In [16]:
name = "Justin" #string
type(name)

str

In [21]:
name[2] #reference particular element of string name using 0-indexed value

's'

In [23]:
print('First letter = ', name[0])

First letter =  J


In [27]:
name[2:5] #slice of string name up to but not including the 5th element (0-indexed)

'sti'

In [29]:
name[2:]# returns element 2 through the end of the string 

'stin'

In [30]:
name[0:-1] #-1 indicates the last element

'Justi'

In [36]:
print(name + ' Coker') #append to string using additing
print(name*2) #repeat twice
print(name.upper()) #upper case .lower() lower case

Justin Coker
JustinJustin
JUSTIN


Lists

In [41]:
num_list= [4, 5, 6]
num_list[0:2]

[4, 5]

In [43]:
string_list= ['A', 'B', 'C', 1, 2, 3]
print(string_list)
string_list[3] = 2 #element assignment
string_list

['A', 'B', 'C', 1, 2, 3]


['A', 'B', 'C', 2, 2, 3]

In [45]:
#iterate over lists
for x in string_list:
    print(x)

A
B
C
2
2
3


In [51]:
#addition with lists appends 1 list to another

num_list + string_list

[4, 5, 6, 'A', 'B', 'C', 2, 2, 3]

In [52]:
#prints reverse a list
num_list[::-1]

[6, 5, 4]

In [57]:
#reverses num_list and assigns it to the variable
num_list.reverse()
num_list

#remove a value
num_list.remove(4)

In [58]:
num_list

[6]

In [61]:
num_list= [4, 5, 6]
del(num_list[2]) #remove a certain element
num_list

[4, 5]

Tuples are ordered collections, immutable

In [64]:
num_tuple = (8, 9, 10) #same index, slicing, apending properties of lists

In [68]:
num_tuple[0] = 10 #but unmutable

TypeError: 'tuple' object does not support item assignment

Range is a sequence of numbers, typically used in a loop

In [75]:
x=range(1, 5)
for i in x: #0 indexed
    print(i)

1
2
3
4


In [76]:
x=range(0, 100, 10) #3rd arguement is the step size
for i in x: #0 indexed
    print(i)

0
10
20
30
40
50
60
70
80
90


Set: collection of unordered, unique objects

In [78]:
num_set= {1, 1, 2, 2, 2, 10, 12}
num_set

{1, 2, 10, 12}

In [79]:
4 in num_set #conditional

False

In [80]:
num_set = {3, 5, 7, 2}
num_set #order does not matter

{2, 3, 5, 7}

In [81]:
for i in num_set: #can still iterate
    print(i)

2
3
5
7


Dictionaries: provides a mapping from some unique key to specific object

In [82]:
address_dict = {'street': 'Greene St.', 'number': 1014, 'City': 'Columbia', 'State': 'SC'}

In [85]:
address_dict['City'] #indexed by the key

'Columbia'

In [86]:
for v in address_dict.values():
    print(v)

Greene St.
1014
Columbia
SC


In [87]:
for k in address_dict.keys():
    print(k)

street
number
City
State


In [89]:
for k, v in address_dict.items():
    print('Key= ', k, 'Value= ', v)

Key=  street Value=  Greene St.
Key=  number Value=  1014
Key=  City Value=  Columbia
Key=  State Value=  SC


NumPy

In [91]:
import numpy as np

In [95]:
# a np array
x= np.array([[1, 2], [3, 4]])

x

array([[1, 2],
       [3, 4]])

In [97]:
x + x #matrix operations on the lists

array([[2, 4],
       [6, 8]])

In [101]:
x * x  #element by element multiplication

array([[ 1,  4],
       [ 9, 16]])

In [103]:
np.dot(x, x) #matrix multiplication

array([[ 7, 10],
       [15, 22]])

In [104]:
np.kron(x, x)

array([[ 1,  2,  2,  4],
       [ 3,  4,  6,  8],
       [ 3,  6,  4,  8],
       [ 9, 12, 12, 16]])