# NumPy Broadcasting

Two arrays will be broadcast together if they are same size or if one of the dimensions are the same and the other is of size 1

In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2], [3, 4]])

B =  np.array([[2, 5]])

In [5]:
print(B.shape)
print(A.shape)

(1, 2)
(2, 2)


In [7]:
A * B # A(1,1)*B(1,1)  A(1,2)*B(1,2)
      # A(2,1)*B(1,1)   A(2, 2)*B(1,2)

array([[ 2, 10],
       [ 6, 20]])

In [8]:
np.ones((2, 2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [9]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Reshaping arrays

In [13]:
A.reshape((4, 1)) #reshapes the 2,2 A array to a 4 by 1 array of the same elements

array([[1],
       [2],
       [3],
       [4]])

In [14]:
A #reshape does not change original array

array([[1, 2],
       [3, 4]])

In [15]:
D = np.tile(A, (1,1,4))

In [17]:
D #a matrix of A repeated 4 times

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]]])

In [18]:
D.shape

(1, 2, 8)

In [19]:
D = np.tile(A.reshape((2,2,1)), (1,1,4))

In [21]:
print(D)
D.shape

[[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]]


(2, 2, 4)

# Pandas

In [23]:
import pandas as pd

In [24]:
# create a dictionary with data
data = {'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'], 'year': [2014, 2015, 2016, 2015, 2016], 
       'wins': [6, 5, 5, 10, 8]}

In [25]:
data

{'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'],
 'wins': [6, 5, 5, 10, 8],
 'year': [2014, 2015, 2016, 2015, 2016]}

In [26]:
df = pd.DataFrame(data)

In [27]:
df

school  wins  year
0  Texas     6  2014
1  Texas     5  2015
2  Texas     5  2016
3    UGA    10  2015
4    UGA     8  2016

In [29]:
df.columns #list of col names

Index(['school', 'wins', 'year'], dtype='object')

In [30]:
df.columns.tolist()

['school', 'wins', 'year']

In [33]:
df['wins']

0     6
1     5
2     5
3    10
4     8
Name: wins, dtype: int64

In [34]:
df.loc[4]

school     UGA
wins         8
year      2016
Name: 4, dtype: object

In [37]:
df.loc[0:2]

school  wins  year
0  Texas     6  2014
1  Texas     5  2015
2  Texas     5  2016

In [39]:
df.groupby(['school'])['wins'].sum()

school
Texas    16
UGA      18
Name: wins, dtype: int64

In [42]:
df.groupby(['school'])['wins'].describe()

count      mean       std  min  25%  50%  75%   max
school                                                     
Texas     3.0  5.333333  0.577350  5.0  5.0  5.0  5.5   6.0
UGA       2.0  9.000000  1.414214  8.0  8.5  9.0  9.5  10.0

In [44]:
df['wins squared'] = df['wins'] ** 2
df

school  wins  year  wins squared
0  Texas     6  2014            36
1  Texas     5  2015            25
2  Texas     5  2016            25
3    UGA    10  2015           100
4    UGA     8  2016            64

In [45]:
df.head(n=3)

school  wins  year  wins squared
0  Texas     6  2014            36
1  Texas     5  2015            25
2  Texas     5  2016            25

In [53]:
#rename cols
df.rename(columns = {"wins": "Wins", "wins squared": "wins sq"}, inplace = True) 
#dict of form (oldname: newname, oldname: newname...)
#inplace =  True, replaces df with a dataframe with new col names

In [54]:
df

school  Wins  year  win sq
0  Texas     6  2014      36
1  Texas     5  2015      25
2  Texas     5  2016      25
3    UGA    10  2015     100
4    UGA     8  2016      64

# Reading data

In [2]:
ls

BuiltinTypes.ipynb*    Notes.pdf*             PythonNumpyPandas.ipynb*
Comp_Econ_8-31.ipynb*  NumpyIntro.pdf*        PythonReadIn.ipynb*
CompEcon_9-5.ipynb*    OOP.pdf*               PythonReshape.ipynb*
DataFiles/             PS2.pdf*               README.md*
DataFunctions.ipynb*   PythonBasics.ipynb*    StandardLibrary.pdf*
fibo.py*               PythonDescribe.ipynb*
kisa_2015.csv*         PythonFuncs.ipynb*


In [10]:
#kisa_2015.csv
import csv

kisa_data = list(csv.reader(open('kisa_2015.csv'))) 
#read into a list of lists where each element is a row of the csv data
len(kisa_data)

96

In [14]:
kisa_data[1][3] #row 1, column 3...note even numerical data are strings

'57'

In [20]:
# import into a np array
import numpy as np
kisa_data = np.genfromtxt('kisa_2015.csv', delimiter = ",", skip_header = 1)#skips first row

In [21]:
kisa_data[:5] #gets numerical data, but cannot handle strings

array([[  1.20000000e+01,   4.20000000e+01,   5.00000000e+00,
          5.70000000e+01,   4.00000000e+00,   1.00000000e+00,
          1.40000000e+01,   4.00000000e+01,   1.00000000e+00,
          5.70000000e+01,   4.93400000e+04,   2.00000000e+00,
          1.50000000e+01,  -1.00000000e+00,   1.00000000e+00,
          2.01400000e+03,   4.00000000e+00,   1.00000000e+00,
          3.03298119e+03,   8.19000000e+03,   1.00000000e+01,
          8.19000000e+03,   1.00000000e+01,              nan,
          2.01500000e+03,   1.00000000e+00,   0.00000000e+00,
                     nan,   4.00000000e+01,   4.00000000e+01,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   2.69172442e+02,
          2.70433824e+02],
       [  1.20000000e+01,   3.90000000e+01,   7.00000000e+00,
          2.60000000e+01,   4.00000000e+00,   1.00000000e+00,
          1.40000000e+01,   4.00000000e+01,   1.00000000e+00,
          5.70000000e+01,   4.93400000e+04,

In [25]:
np.mean(kisa_data[:, 3]) #mean of column 3, all rows

43.178947368421049

In [27]:
import pandas as pd
#pandas
kisa_data = pd.read_csv('kisa_2015.csv')

In [30]:
kisa_data.head() #can handle strings, numerical, etc. missing values will be NaN

month  grdatn  marstat  age  class  region  state  hours  mlr  natvty  \
0     12      42        5   57      4       1     14     40    1      57   
1     12      39        7   26      4       1     14     40    1      57   
2     12      41        1   43      4       2     41     46    1     110   
3     12      39        1   38      4       2     41     40    1      57   
4     12      42        1   51     -1       3     58     -1    6      57   

      ...      homeown  hoursu1b  hoursu1b_t1  se15u  se15u_t1  ent015u  \
0     ...          NaN        40           40      0         0      0.0   
1     ...          NaN        40           40      0         0      0.0   
2     ...          NaN        46           40      0         0      0.0   
3     ...          NaN        40           30      0         0      0.0   
4     ...          NaN        -1           -1      0         0      0.0   

   ent015ua  vet       wgtat      wgtat1  
0       0.0    0  269.172442  270.433824  
1       0.0    0  403.023478  404.912105  
2       0.0    0  402.790075  404.677609  
3       0.0    0  342.934489  344.541531  
4       0.0    0  560.224448  562.849743  

[5 rows x 37 columns]

In [31]:
kisa_data.describe()

month     grdatn    marstat        age      class     region  \
count   95.0  95.000000  95.000000  95.000000  95.000000  95.000000   
mean    12.0  40.284211   2.568421  43.178947   2.810526   3.210526   
std      0.0   2.562675   2.434908  11.816846   2.531902   0.921317   
min     12.0  34.000000   1.000000  20.000000  -1.000000   1.000000   
25%     12.0  39.000000   1.000000  33.500000  -1.000000   3.000000   
50%     12.0  40.000000   1.000000  44.000000   4.000000   3.000000   
75%     12.0  43.000000   5.000000  52.000000   4.000000   4.000000   
max     12.0  46.000000   7.000000  64.000000   7.000000   4.000000   

           state      hours        mlr      natvty     ...      homeown  \
count  95.000000  95.000000  95.000000   95.000000     ...          0.0   
mean   69.084211  27.673684   2.557895   88.473684     ...          NaN   
std    23.262454  21.014403   2.499854   79.168799     ...          NaN   
min    14.000000  -1.000000   1.000000   57.000000     ...          NaN   
25%    63.000000  -1.000000   1.000000   57.000000     ...          NaN   
50%    71.000000  40.000000   1.000000   57.000000     ...          NaN   
75%    86.000000  41.500000   5.500000   57.000000     ...          NaN   
max    94.000000  65.000000   7.000000  364.000000     ...          NaN   

        hoursu1b  hoursu1b_t1      se15u   se15u_t1  ent015u  ent015ua  \
count  95.000000    95.000000  95.000000  95.000000     87.0      85.0   
mean   27.315789    27.221053   0.073684   0.084211      0.0       0.0   
std    20.111531    20.316212   0.262642   0.279177      0.0       0.0   
min    -1.000000    -1.000000   0.000000   0.000000      0.0       0.0   
25%    -1.000000    -1.000000   0.000000   0.000000      0.0       0.0   
50%    40.000000    40.000000   0.000000   0.000000      0.0       0.0   
75%    40.000000    40.000000   0.000000   0.000000      0.0       0.0   
max    65.000000    70.000000   1.000000   1.000000      0.0       0.0   

             vet       wgtat      wgtat1  
count  95.000000   95.000000   95.000000  
mean    0.084211  320.829357  322.332811  
std     0.279177  127.035039  127.630344  
min     0.000000   40.806662   40.997888  
25%     0.000000  244.629113  245.775481  
50%     0.000000  351.493054  353.140203  
75%     0.000000  405.081462  406.979734  
max     1.000000  600.702105  603.517084  

[8 rows x 36 columns]

In [32]:
kisa_data['age'].mean()

43.17894736842105

In [37]:
import pickle

pickle.dump(kisa_data, open('kisa_df.pkl', 'wb')) #wb allows for compatability across OS

In [35]:
kisa2 = pickle.load(open('kisa_df.pkl', 'rb'))

In [36]:
kisa2

month  grdatn  marstat  age  class  region  state  hours  mlr  natvty  \
0      12      42        5   57      4       1     14     40    1      57   
1      12      39        7   26      4       1     14     40    1      57   
2      12      41        1   43      4       2     41     46    1     110   
3      12      39        1   38      4       2     41     40    1      57   
4      12      42        1   51     -1       3     58     -1    6      57   
5      12      42        1   50      4       3     58     50    1      57   
6      12      39        7   33      4       1     16     -1    4      57   
7      12      40        4   52      5       1     16     42    1      57   
8      12      43        1   41      4       4     81     30    1      57   
9      12      39        1   43      6       4     81     40    1      57   
10     12      44        1   43      5       3     56     30    1      57   
11     12      44        1   45      4       3     56     65    1      57   
12     12      40        1   64      3       4     93     40    1      57   
13     12      43        1   54      2       4     93     20    1      57   
14     12      43        1   28      4       3     59     50    1      57   
15     12      39        1   28      4       3     59     50    1      57   
16     12      39        1   48      4       3     63     60    1      57   
17     12      42        1   46      5       3     63     40    1      57   
18     12      39        1   44      4       3     63     52    1      57   
19     12      40        1   40      4       3     63     40    1      57   
20     12      43        1   43      4       3     63     45    1      57   
21     12      39        1   41      3       3     63     40    1      57   
22     12      39        1   21      4       3     63     38    1      57   
23     12      39        1   20      4       3     63     40    1      57   
24     12      39        1   63     -1       3     63     -1    5      57   
25     12      39        7   35     -1       3     63     -1    7      57   
26     12      43        5   54      4       3     63     45    1      57   
27     12      39        4   54     -1       3     63     -1    6      57   
28     12      38        7   52      4       3     63     15    1      57   
29     12      43        1   57      4       3     63     45    1      57   
..    ...     ...      ...  ...    ...     ...    ...    ...  ...     ...   
65     12      44        1   29      4       4     86     -1    2      57   
66     12      39        1   30      2       4     86     40    1      57   
67     12      36        3   38      4       4     86     40    1     303   
68     12      43        1   46      7       4     86     15    1     217   
69     12      43        1   50      4       4     86     40    1     217   
70     12      35        1   40     -1       4     86     -1    7     303   
71     12      35        1   47      4       4     86     40    1     303   
72     12      37        1   24     -1       4     86     -1    7      57   
73     12      38        1   30      4       4     86     38    1      57   
74     12      40        5   40      4       4     86     50    1     303   
75     12      43        7   57     -1       4     86     -1    6      57   
76     12      44        1   43      2       3     54     50    1      57   
77     12      43        1   43     -1       3     54     -1    7      57   
78     12      40        1   46      7       3     71     32    1      57   
79     12      43        1   51      4       3     71     50    1      57   
80     12      39        5   54      7       3     71     48    1     248   
81     12      39        5   61     -1       3     71     -1    6      57   
82     12      39        1   58     -1       3     71     -1    6      57   
83     12      36        1   52     -1       3     71     -1    7      57   
84     12      40        7   36     -1       3     71     -1    7      57   


# Functions

In [40]:
def product(val1, val2):
    prod = val1 * val2
    
    return prod

In [41]:
product(5, 10)

50

In [44]:
# lambda fn

f = lambda x, y: x*y #takes inputs x, y and returns everything after : (product)
f(4, 5)

20